### ISSUE TITLE
ErrorBoundary Prop types

### ISSUE THREAD

**Issue by wobsoriano** [brophdawg11/remix-routers#4]
Hi! Browsing around and saw the comment [here](https://github.com/brophdawg11/remix-routers/blob/main/packages/vue/src/remix-router-vue.ts#L330). I think we can do something like this:

```ts
import type { PropType } from 'vue'

const ErrorBoundary = defineComponent({
  name: "ErrorBoundary",
  // TODO: Can we do anything with typing here?  Error can be anything so it
  // doesn't like `type`
  // props: ["component", "error"],
  props: {
    component: {
      type: Object as PropType<Component>,
      required: true
    },
    error: {
      type: Object as PropType<Error | Record<string, unknown>> // or just Error
    }
  }
});
```

I can PR if this looks good 😄

**Comment by brophdawg11** [comment]
Oh awesome, that looks like exactly what I was looking for.  Yeah that would be great if you wanted to open a PR, I took the easy way around that one for sure :)

**Comment by wobsoriano** [comment]
Okay PR'd a simple update 😄
